### ISSUE TITLE
Adding additional items within the FuzzyWrapper

### ISSUE THREAD

**Issue by Luciam91** [1egoman/fuzzy-picker#14]
Is it currently possible to add additional items within the `FuzzyWrapper` component such as clickable links to exit the dialog?

If not I can look into adding this.

**Comment by 1egoman** [comment]
I don't believe so, though if you want to manage the control of opening and closing the fuzzy picker, it might be better to extract [the logic out of `FuzzyWrapper` that does this](https://github.com/1egoman/fuzzy-picker/blob/master/src/fuzzy-wrapper.js#L12-L24) and add it to your own component, which then can render a `FuzzyPicker` component on its own, surrounding it with whatever other user interface components you'd like.

IMO (and my opinion could be changed), I think that if a user wants something more advanced then just rendering the picker then it probably makes sense to effectively write your own `FuzzyWrapper`, given the component isn't all that complicated and the majority of the logic is ~10 loc.

**Comment by Luciam91** [comment]
This makes sense :)

If this isn't something you want to add to the package we can create our own component and go from there.

Thanks!

**Comment by 1egoman** [comment]
Yep, I think I'd prefer to keep the `FuzzyWrapper` component as simple as possible, especially since writing your own wrapper should be so simple.
