### ISSUE TITLE
Fuzzy picker doesn't close on enter

### ISSUE THREAD

**Issue by ashleydavis** [1egoman/fuzzy-picker#17]
Hi @1egoman , I've been looking over the code trying to figure out why 'enter' doesn't dismiss my fuzzy picker.

When I look at the code for handling 'escape' it includes a call to `onClose`:

```
        case 'Escape':
          {
            this.setState({ items: this.getInitialItems() });
            this.props.onClose();
          }
```

Looking at the code for 'enter' you can see that it doesn't call `onClose`:

```
        case 'Enter':
          {
            // Enter key
            var item = this.state.items[this.state.selectedIndex];
            if (item) {
              this.setState({ items: this.getInitialItems() });
              this.props.onChange(item);
            }
            break;
          }
```

If I change this to include `onClose` it works the way I expected it to, this is the updated code:

```
        case 'Enter':
          {
            // Enter key
            var item = this.state.items[this.state.selectedIndex];
            if (item) {
              this.setState({ items: this.getInitialItems() });
              this.props.onChange(item);
>>            this.props.onClose();
            }
            break;
          }
```

So I'm just wondering how your demo works? 

How did you intend this to work? Is `onClose` supposed to be called automatically when the user hits enter?

If you are happy with placement of `onClose` in the previous code snippet please let me know and I'll update the code and submit a PR.

Thanks
Ash

**Comment by 1egoman** [comment]
> So I'm just wondering how your demo works?

Here's how it works: calling `onChange` calls `onClose` outside of the context of the component: https://github.com/1egoman/fuzzy-picker/blob/master/docs/script.js#L30

I seem to remember doing this intentionally so that a user could do whatever they wanted when they selected an item in the picker - ie, maybe they would want to change the contents of the picker and allow the user to pick something else? But you're correct in saying that `onClose` is never called when the user presses enter.

What do you think of this behavior? I hadn't meant for it to be surprising but maybe it is. Does this additional clarification make sense, or do you think this behavior is more confusing than useful?

**Comment by ashleydavis** [comment]
It certainly confused me.

The picker says 'ENTER to close'  in the UI so I thought that would just work. 

Will have a look at the code you linked tomorrow. Thx!

**Comment by ashleydavis** [comment]
Actually this is my mistake - it doesn't say 'ENTER to close', that's just my bad memory.

It says "enter to select" which says it all really.

I've looked at the example you linked to me. I was thinking what I would do is update the README to document how to make the fuzzy picker close on enter, although your demo implementation is significantly different to the example in the README, so I don't think it's a simple case to just update that.

How about I add a new property `automaticCloseOnEnter` that automatically closes the fuzzy picker when the user presses enter? 

Then I can enable that property in the example in the README and add a note to say that by default this feature is disabled so that you can handle the enter key how you want.

**Comment by 1egoman** [comment]
> How about I add a new property automaticCloseOnEnter that automatically closes the fuzzy picker when the user presses enter?

That sounds fine.

**Comment by ashleydavis** [comment]
PR #18 adds the new property.

**Comment by 1egoman** [comment]
#18 is merged, I can this be closed @ashleydavis?

**Comment by ashleydavis** [comment]
Awesome, thanks. I have more changes coming!
