### ISSUE TITLE
Support for arrays of objects as items

### ISSUE THREAD

**Issue by oyeanuj** [1egoman/fuzzy-picker#6]
Hi @1egoman! Thanks for putting out this library! 

I noticed that the examples and documentation refer to items as an array of strings. Can the library today or will it in the future support items being objects rather than strings? 

This would allow for more information being passed to the callback function, as well, as being able to search on more than just a string.

**Comment by 1egoman** [comment]
@oyeanuj Glad you like the project!

I've already ran into this problem in my own projects, and it's on my shortlist of features to work on soon. That being said, I'm still trying to think through exactly how I want to do it.

One idea I had was to implement an optional custom function that would map items to a component that would be rendered for each list item:
```javascript
<FuzzyPicker
  items=[{value: "foo"}, {value: "bar"}]}
  listItemComponent={item => <span>{item.value}</span>}
/>
```
I haven't done this yet mostly because I'm still trying to figure out a good way to document it / have a cool example that get's the point across.

Another idea I had was to just have a prop that was the key to be "extracted" in nested objects. Not sure how extensible this would be in the long term. Something like:
```javascript
<FuzzyPicker
  items=[{value: "foo"}, {value: "bar"}]}
  llistItemKey="value"
/>
```
But that isn't quite as flexible, and in general, doesn't sit well with me.

Love to hear your and others feedback on this, or if there's an even better way I didn't think of let me know.

**Comment by oyeanuj** [comment]
@1egoman Thanks for the detailed response. I feel like the first option seems the most flexible, and clean to me. 

FWIW, React-Virtualized and React-Autosuggest are two popular libaries with similar sort of patterns. I think RV uses the first pattern you mentioned, and seems the cleanest.

**Comment by 1egoman** [comment]
@oyeanuj Had some time last weekend so I put this feature together. Here's what I have so far - https://github.com/1egoman/fuzzy-picker/pull/8.

Feel free to let me know what you think.

**Comment by Luciam91** [comment]
Hey @1egoman, is there any update on this? Just ran into this exact issue when trying to use this as a command palette!

**Comment by 1egoman** [comment]
@Luciam91 I was able do make some headway a while back, see this PR: https://github.com/1egoman/fuzzy-picker/pull/8

I wanted to do a bit more on it, but I think it's fine to merge as is since it's been open so long.

**Comment by 1egoman** [comment]
Just merged and pushed `v0.5.0`. Let me know if that's helpful!

**Comment by Luciam91** [comment]
Hmmm, using the hard-coded array with objects it works fine, but when I'm trying to use an array of objects from the state nothing seems to be returned by the search

**Comment by 1egoman** [comment]
@Luciam91 Can you provide an example?

**Comment by Luciam91** [comment]
Not a problem

```js
import React, { Component, PropTypes } from 'react';
import { connect } from 'react-redux';
import FuzzyPicker, { FuzzyWrapper } from 'react-fuzzy-picker';

class CommandPalette extends Component {
  static propTypes = {
    spaces: PropTypes.arrayOf(PropTypes.shape({
      identifier: PropTypes.string.isRequired,
      name: PropTypes.string.isRequired,
    })).isRequired,
  };

  isCorrectKeyPressed = e => e.key === '/';

  renderFuzzyPicker = (isOpen, onClose) =>
    <FuzzyPicker
      isOpen={isOpen}
      onClose={onClose}
      onChange={choice => console.log('You picked', choice)}
      items={this.props.spaces}
      itemValue={item => item.name}
    />;

  render() {
    return (
      <div>
        <FuzzyWrapper
          isKeyPressed={this.isCorrectKeyPressed}
          popup={this.renderFuzzyPicker}
        />
      </div>
    );
  }
}

const mapStateToProps = state => (
  {
    spaces: state.spaces.list || [],
  }
);

const mapDispatchToProps = () => (
  {}
);

export default connect(mapStateToProps, mapDispatchToProps)(CommandPalette);
```

When I add console log statements to `renderFuzzyPicker` I can see on very first load of the page that it's an empty array, but then it reloads with the state and outputs the array I expect but no text search works at all.

Example array:

```js
[{"id": 123, "name": "Scott"},{"id":456, "name": "David"}]
```

**Comment by 1egoman** [comment]
@Luciam91 I think you forgot the `renderItem` prop for the `FuzzyPicker` component. Here's an example of its usage: https://github.com/1egoman/fuzzy-picker/blob/master/docs/script.js#L100 

After reading through the readme, I added some more documentation to make it more clear that `itemValue` and `renderItem` must be used together. Here's some documentation on the props that a `FuzzyPicker` accepts: https://github.com/1egoman/fuzzy-picker#fuzzypicker

Sorry for the confusion!

**Comment by Luciam91** [comment]
No problem! I've added that but it still doesn't work :(
It appears to trigger twice but I don't know if the empty list is the one that's not being used, this is the output from console.log

```js
index.js:30 []
index.js:30 [{"identifier":"3bf8ce6e-871f-4149-bfa6-a6cb0000c6fb","name":"Scott Pringle Default Space"}]
```

Console.log triggers again when I actually open the display and it outputs the same as the second line above

**Comment by 1egoman** [comment]
@Luciam91 I had to modify your example a bit to use some older js features, but this works for me:

```javascript
import {FuzzyPicker, AsyncFuzzyPicker, FuzzyWrapper} from '../src';
import React from 'react';
import ReactDOM from 'react-dom';

class CommandPalette extends React.Component {
  isCorrectKeyPressed(e) {
    return e.key === '/';
  }

  renderFuzzyPicker(isOpen, onClose) {
    return <FuzzyPicker
      isOpen={isOpen}
      onClose={onClose}
      onChange={choice => console.log('You picked', choice)}
      items={this.props.spaces}
      itemValue={item => item.name}
      renderItem={item => <span>{item.name}</span>}
    />;
  }

  render() {
    return (
      <div>
        <FuzzyWrapper
          isKeyPressed={this.isCorrectKeyPressed}
          popup={this.renderFuzzyPicker.bind(this)}
        />
      </div>
    );
  }
}

ReactDOM.render(<CommandPalette
	spaces={[{"id": 123, "name": "Scott"},{"id":456, "name": "David"}]}
/>, document.getElementById('react'));
```

<img width="468" alt="screen shot 2017-07-06 at 5 52 24 pm" src="https://user-images.githubusercontent.com/1704236/27934538-4134d87e-6274-11e7-9653-7c8c3b4df528.png">

Can you confirm that the `renderItem` prop renders jsx that is valid? (When hacking together the above, I forgot to swap out `item.value` => `item.name` and saw something similar to what you described)

I tried this out in the example code for https://1egoman.github.io/fuzzy-picker, available [here](https://github.com/1egoman/fuzzy-picker/blob/master/docs/script.js), and ran `gulp example` to build and serve it.

**Comment by Luciam91** [comment]
Using the example you've got works, but as soon as I try to get the data from the Redux store nothing can be searched, I'm assuming this is due to Redux doing an initial load with nothing and then reducers kicking in to fill the state?

**Comment by 1egoman** [comment]
@Luciam91 That's likely it. As a workaround, wrap the fuzzy picker in a conditional (see below), or I just pushed a small update that I suspect will fix this: https://github.com/1egoman/fuzzy-picker/commit/ec2dfa760a0b09e401c1b12bb686438a039082e7 (this is `v0.5.1`)

```javascript
  // Potential workaround
  renderFuzzyPicker(isOpen, onClose) {
    if (this.props.spaces.length) {
      return <FuzzyPicker
        isOpen={isOpen}
        onClose={onClose}
        onChange={choice => console.log('You picked', choice)}
        items={this.props.spaces}
        itemValue={item => item.name}
        renderItem={item => <span>{item.name}</span>}
      />;
    } else {
      return null;
    }
  }
```


To validate my patch, I ran this:
```javascript
import {FuzzyPicker, AsyncFuzzyPicker, FuzzyWrapper} from '../src';
import React from 'react';
import ReactDOM from 'react-dom';

// A class to wrap our example and maintain its state
class FuzzySearchExample extends React.Component {
  constructor(props) {
    super(props);
		this.state = {
			items: [],
		};

		setTimeout(() => {
			this.setState({items: [{value: "foo"}, {value: 'bar'}, {value: 'baz'}]});
		}, 2000);
  }
  render() {
    return <div>
      {this.state.choice ? <p>
        You picked: <code>{this.state.choice.value}</code>!
      </p> : <span>
        <p>
          Give it a try!
        </p>
        <p>
          Press <code>/</code> to open and try searching for <code>lorem</code>!
        </p>
      </span>}

      <FuzzyPicker
        {...this.props}
        onChange={choice => {
          this.setState({choice});
          this.props.onClose();
        }}

        label="Search for a thing!"
        items={this.state.items}

        itemValue={item => item.value}
        renderItem={item => <span className="item-wrapper">{item.value}</span>}
      />
    </div>;
  }
}

// Use the FuzzyWrapper to control whether the fuzzy searcher is open or not.
ReactDOM.render(<FuzzyWrapper
  isKeyPressed={e => {
    // Press slash.
    return e.key === '/';
  }}
  popup={(isOpen, onClose) => <FuzzySearchExample isOpen={isOpen} onClose={onClose} />}
/>, document.getElementById('react'));
```

Is either the new version or the above patch solve your issue?

**Comment by Luciam91** [comment]
Bumping to 0.5.1 works, thank you very much @1egoman! :D
