### ISSUE TITLE
Closing box programatically

### ISSUE THREAD

**Issue by Luciam91** [1egoman/fuzzy-picker#9]
Currently we have a system that changes page using a Redux push from `react-redux-router` but we need to shut the picker automatically when this push happens.

Apologies if I've been blind but I've not been able to find a way to do this easily (as opposed to the `onClose` method

**Comment by Luciam91** [comment]
Any word on this? :)

**Comment by 1egoman** [comment]
Yikes, looks like I didn't get notified on this, sorry! Just seeing it now.

If you wanted to control the box programmatically, you should be able to use the controlled variant and store the value passed to the `isOpen` prop in redux. Using the `FuzzyWrapper` wouldn't work in this case given that it controls the value of `isOpen` for you. For example:

```javascript
// Reducer
function myFuzzyPickerOpenReducer(state=false, action) {
  switch (action.type) {
    case 'OPEN_FUZZY_PICKER': return true;
    case 'CLOSE_FUZZY_PICKER': return false;
    default: return state;
}

// Then, somehow in the react layer, use the state that is controlled by the reducer to control the `isOpen` prop. 

import FuzzyPicker from 'react-fuzzy-picker';
function MyFuzzyPicker({isOpen}) {
  return <FuzzyPicker
    isOpen={isOpen}
    onClose={() => console.log('You closed the fuzzy-picker')}
    onChange={choice => console.log('You picked', choice)}
    items={["foo", "bar", "baz"]}
  />;
}

// The below is using `react-redux`, but the same could be accomplished in other ways too:
const ConnectedMyFuzzyPicker = connect(state => ({
  isOpen: state.myFuzzyPickerOpenReducer, /* or something like that */
}))(MyFuzzyPickerReducer);

// Then use `ConnectedMyFuzzyPicker`:
<ConnectedMyFuzzyPicker />
```

Does that make sense?

**Comment by Luciam91** [comment]
It does; thank you for responding when you noticed :D 

This was pretty much what I implemented anyway so thank you!
